Feature/24 home inflate
TeamRecorDream/RecorDream-Aos pull request #73
Opened 2023-06-29 17:44 UTC by urjimyu

## 👻 작업한 내용

## 🎤 PR Point

- 클릭 후 상세보기로 넘어가면 해당 카드 정보가 반영되어 있지 않은 상태인데 이건 상세보기뷰 관련 브랜치에서 해결해야 할 것 같아서 일단 풀리퀘 날립니다.
- 현재 카드 그림자 적용 안된 이미지 사용중인데 기능 해결 후 고치겠습니다.
- 새로고침 기능 완료!
-  홈화면 카드 이모티콘 이미지가 이상한 게 겹쳐서 뜨는 상황 해결 완료!
- 닉네임 반영 완료!

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 홈뷰에서 카드 불러와서 띄워주기| <img width="208" alt="Screenshot 2023-06-30 at 2 43 42 AM" src="https://github.com/TeamRecorDream/RecorDream-AOS/assets/92876819/67667c1c-55c5-4478-bfd3-377834aa0389"> |
| 홈뷰 및 보관함 뷰에서 카드 누르면 상세보기로 이동|  |

## 📮 관련 이슈

- Resolved: #24

2023-06-29 18:12 UTC, cbj0010 requested changes
리뷰 반영해줘잉

2023-06-29 18:12 UTC, cbj0010 commented on app/google-services.json
지워주세용~~
이거 remote에 올리시면 안되는건데.. 뭐지 이상하네.. git ignore에도 등록되어 있는데..

2023-06-29 18:12 UTC, cbj0010 commented on app/src/main/java/com/recodream_aos/recordream/data/entity/remote/response/ResponseDocument.kt
> +    @SerialName("_id")
이거 _는 지워주는게 좋다고 그럤습니당

2023-06-29 18:12 UTC, cbj0010 commented on app/src/main/java/com/recodream_aos/recordream/data/entity/remote/response/ResponseHome.kt
> +        @SerialName("_id")
_

2023-06-29 18:12 UTC, cbj0010 commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
>  //    }
요거 지워줘도 되지 않을까용?

2023-06-29 18:12 UTC, cbj0010 commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +                binding.tvHomeHiOff2.visibility = View.INVISIBLE
아이 변수명 맘에 안들어라잉~

2023-06-29 18:12 UTC, cbj0010 commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomePagerRecyclerAdapter.kt
>  //        homeCardList = list
로그 지워줘잉~

2023-06-29 18:12 UTC, cbj0010 commented on app/src/main/res/layout/fragment_home.xml
> +            android:id="@+id/tv_home_hi_off2"
1,2 이런거보다 길어져도 되니 상세하게 적어보는건 어떨까요?

2023-06-29 18:16 UTC, urjimyu commented on app/google-services.json
ㅠㅜ없애버리겠어,,

2023-06-30 02:27 UTC, s9hn approved these changes
고생하셨습니다~

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/data/entity/remote/response/ResponseDocument.kt
> +    @SerialName("_id")
_를 지우면 에러가 날 것 같아요
@SerialName은 우리가 Json객체로 직렬화할 때 나타낼 프로퍼티 이름을 지정하는 어노테이션입니다.
서버에선 리스폰스 바디로 _id로 요구하고 있으므로 해당코드는 괜찮아보입니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/data/entity/remote/response/ResponseDocument.kt
> +    @SerialName("writer")
추가적으로 아래에 일괄적으로 적용되는 리뷰이지만,
위에서 말했듯이 SerialName은 직렬화 시 직렬화될 객체의 프로퍼티 이름을 지정하는 어노테이션입니다
data class의 프로퍼티명과 SerialName으로 지정해준 프로퍼티명이 같다면, 굳이 어노테이션을 모두 붙여줄 필요는 없습니다.
해당 어노테이션이 어느상황에 필요하고 왜 써야하는지 알아보면 좋을 것 같습니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/data/entity/remote/response/ResponseDocument.kt
> +    @SerialName("writer")
저는 개인적으로 서버에서 요구한 리스폰스/리퀘스트 바디의 프로퍼티명이 의도와 많이 다른게 아니라면 SerialName 사용이 별로 좋지 않아보입니다. 직렬화 라이브러리를 교체할 때 불편합니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/data/repository/DocumentRepositoryImpl.kt
> +        } catch (e: Exception) {
try-catch보단 kotlin에서 제공하는 runcatching을 활용해봅시다.
추가로 해당 서버코드의 출발점은 레포지토리가 아닌 뷰모델일것 같은데, 이런 핸들링은 출발점에서 해주는게 좋아보입니다.

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/data/repository/HomeRepositoryImpl.kt
> +            Log.d("babo", "getHomeRecord: $response")
사용하지않는 로그는 지워주는게 좋습니다.
의도된 로그라면, 로그위계에 대해 공부해보셔도 좋습니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/di/ServiceModule.kt
> +//    ): HomeService = retrofit.create(DocumentService::class.java)
사용하지않는 주석이 프로젝트 메인에 머지되고 있습니다.
의도된 바가 아니라면 가급적 지워주시는게 좋습니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/MainActivity.kt
> +        supportFragmentManager.beginTransaction().replace(R.id.fcv_main_navhostfragment, fragment)
replace말고 어떤방법이 있을까요?
replace는 프래그먼트 스택관리를 어떻게 하나요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +            intent.apply { it.id }
수신객체의 사용이 조금은 어색합니다.
수신객체의 종류를 공부해봐도 좋습니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +            val intent = Intent(requireContext(), DocumentActivity::class.java)
DocumentActivity를 호출하는 Intent를 HomeFragment가 만들어야하나요? 
초대장은 집주인이 만드는게 맞지않을까요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +                binding.tvHomeHiOff2.visibility = View.INVISIBLE
@cbj0010 i, i2?
1. visibility는 bindingAdapter와 dataBinding을 활용해볼 수 있을 것 같습니다.
2. View가 ResponseHome이라는 dto에 의존해야할까요?
3. 사용될 데이터의 널처리는 뷰의 책임인가요?
4. 사이즈 검사와 같은 비즈니스로직이 뷰의 책임인가요?
5. 변수명에 숫자로 인한 구분은 지양하면 좋습니다.

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +            } else {
객체지향 생활체조원칙엔
if-else를 지양하자고 합니다. 어떤 방법들이 있을까요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +        (binding.vpHome.adapter as HomeViewPagerAdapter).updateList(data.toMutableList())
HomeViewPagerAdapter.updateList(data)로 끝낼 수 있지 않을까요?
각종 형 변환들을 이 함수에서 해주어야 하나요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomePagerRecyclerAdapter.kt
> +        fun onBind(data: ResponseHome.Record) {
onBind는 데이터별로 계속 호출됩니다.
본 함수가 호출될때마다 클릭리스너를 세팅해주는 번거로운 작업을 반복해야할까요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomePagerRecyclerAdapter.kt
>              binding.tvHomeCardTitle.text = data.title
dataBinding으로 줄일 수 있어보입니다

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomePagerRecyclerAdapter.kt
> +            binding.clHomeCard.setBackgroundResource(checkEmotionBackground(data.emotion))
bindingAdapter를 활용해볼까요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomePagerRecyclerAdapter.kt
> +        fun checkEmotionIcon(color: Int) = when (color) {
해당로직들은 어댑터의 책임인가요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeViewModel.kt
> +        viewModelScope.launch { _homeRecords.value = homeRepository.getHomeRecord()?.data?.records }
린트정리는 생활화해주세요

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeViewModel.kt
> +    fun initServer() {
public으로 열어둔 이유가 있을까요?

2023-06-30 02:27 UTC, s9hn commented on app/src/main/java/com/recodream_aos/recordream/presentation/storagy/fragment/StorageFragment.kt
>          binding.rvStorage.layoutManager = GridLayoutManager(context, 2)
숫자로 바로 직관적으로 표현되는것이 아니라면, 상수처리를 해주시는게 가독성이 좋습니다
숫자 2가 가로인지 세로인지 무엇을 의미하는지 잘 모르겠군요

2023-06-30 14:05 UTC, urjimyu commented on app/src/main/java/com/recodream_aos/recordream/presentation/home/HomeFragment.kt
> +            } else {
response가 null 일 때를 가정해서 early return을 해준다..?

2023-06-30 19:04 UTC, cbj0010 approved these changes
고생티비

2023-06-30 19:04 UTC, cbj0010 commented on app/src/main/java/com/recodream_aos/recordream/data/entity/remote/response/ResponseDocument.kt
> +    @SerialName("writer")
아 맞네여 다른거랑 헷갈렸나봐여 죄송합니당 😓

2023-07-01 11:50 UTC, merged